export const siloData = {
  rows: [
    {
      title: "Row 1",
      silo: [
        {
          id: 1,
          name: "8.1",
          icon: "",
          temp: 10,
          url: "",
        },
        {
          id: 2,
          name: "8.2",
          icon: "",
          temp: 20,
          url: "",
        },
        {
          id: 3,
          name: "8.3",
          icon: "",
          temp: 30,
          url: "",
        },
        {
          id: 4,
          name: "10.1",
          icon: "",
          temp: 40,
          url: "",
        },
        {
          id: 5,
          name: "10.2",
          icon: "",
          temp: 50,
          url: "",
        },
        {
          id: 6,
          name: "10.3",
          icon: "",
          temp: 60,
          url: "",
        },
        {
          id: 7,
          name: "10.4",
          icon: "",
          temp: 70,
          url: "",
        },
      ],
    },
    {
      title: "Row 2",
      silo: [
        {
          id: 8,
          name: "8.4",
          icon: "",
          temp: 70,
          url: "",
        },
        {
          id: 9,
          name: "8.5",
          icon: "",
          temp: 60,
          url: "",
        },
        {
          id: 10,
          name: "8.6",
          icon: "",
          temp: 50,
          url: "",
        },
        {
          id: 11,
          name: "8.7",
          icon: "",
          temp: 40,
          url: "",
        },
        {
          id: 12,
          name: "10.5",
          icon: "",
          temp: 30,
          url: "",
        },
        {
          id: 13,
          name: "10.6",
          icon: "",
          temp: 20,
          url: "",
        },
        {
          id: 14,
          name: "10.7",
          icon: "",
          temp: 10,
          url: "",
        },
        {
          id: 15,
          name: "10.8",
          icon: "",
          temp: 0,
          url: "",
        },
      ],
    },
  ],
};
